package com.example.covid_19_backend.pojo.common;

import java.util.ArrayList;
import java.util.List;

public class Constant {
    public static final String[] Countries = {"Afghanistan","Angola","Antigua and Barbuda","Argentina","Armenia","Andorra","Austria","The Bahamas","Azerbaijan","Bahrain","Albania","Algeria","Bangladesh","Benin","Bhutan","Belize","Bosnia and Herzegovina","Bolivia","Botswana","Barbados","Belarus","Brunei","Bulgaria","Burkina Faso","Myanmar","Burundi","Cape Verde","Cambodia","Cameroon","Chad","Central African Republic","Hong Kong","Congo","DR Congo","Comoros","Costa Rica","Ivory Coast","Croatia","Cuba","Czechia","Cyprus","Denmark","Djibouti","Dominica","Dominican Republic","Egypt","Ecuador","Macao","Eritrea","Equatorial Guinea","Estonia","Eswatini","El Salvador","Ethiopia","Fiji","Finland","France","Gabon","The Gambia","Ghana","Georgia","Greece","Grenada","Guatemala","Guyana","Haiti","Vatican City","Honduras","Guinea-Bissau","Hungary","Iceland","Indonesia","Guinea","Ireland","Israel","Iraq","Jamaica","Jordan","Kenya","Kazakhstan","South Korea","Kyrgyzstan","Iran","Laos","Latvia","Lebanon","Lesotho","Liberia","Kuwait","Kosovo","Libya","Lithuania","Madagascar","Malawi","Maldives","Malaysia","Mali","Malta","Mauritania","Marshall Islands","Mauritius","Moldova","Monaco","Mongolia","Liechtenstein","Montenegro","Morocco","Nepal","New Zealand","Nicaragua","Niger","Namibia","Nigeria","North Macedonia","Norway","Oman","Papua New Guinea","Panama","Paraguay","Philippines","Poland","Portugal","Luxembourg","Qatar","Romania","Saint Lucia","Saint Kitts and Nevis","Saint Vincent and the Grenadines","Samoa","San Marino","São Tomé and Príncipe","Senegal","Saudi Arabia","Seychelles","Serbia","Sierra Leone","Slovakia","Singapore","Mozambique","Somalia","Slovenia","South Africa","South Sudan","Sudan","Sri Lanka","Suriname","Rwanda","Solomon Islands","Taiwan","Tajikistan","Thailand","Tanzania","Timor-Leste","Togo","Switzerland","Turkey","Tunisia","Uganda","United Arab Emirates","Uzbekistan","Uruguay","Vanuatu","Vietnam","Palestine","Trinidad and Tobago","Yemen","Zambia","Kiribati","Zimbabwe","Venezuela","Syria","Palau","India","Brazil","Russia","United Kingdom","Colombia","Italy","Spain","Mexico","Ukraine","United States","Peru","Netherlands","Chile","Canada","Belgium","Sweden","Japan","Pakistan","Australia","Reunion","French Guiana","Germany","Guadeloupe","Mayotte","Martinique","Curacao","Channel Islands","Aruba","Gibraltar","Summer Olympics 2020","Turks and Caicos Islands","Saint Martin","Caribbean Netherlands","Bermuda","Isle of Man","Saint Barthelemy","Faroe Islands","Wallis and Futuna","Cayman Islands","British Virgin Islands","New Caledonia","Falkland Islands","Anguilla","Greenland","Saint Pierre and Miquelon","Montserrat","French Polynesia","Micronesia","Sint Maarten","Western Sahara","Saint Helena"};
    public static final List<String> COUNTRY = new ArrayList<>();
    public static final String[] CONTINENT = {"Asia", "Africa", "Europe", "NorthAmerica", "SouthAmerica", "Oceania"};
    static {
        for (int i = 0; i < Countries.length; ++i) {
            COUNTRY.add(Countries[i]);
        }
    }
    public static final String[] LOCATION = {"中国","台湾","云南","德宏州","昭通市","昆明","保山市","玉溪","红河","曲靖","大理","西双版纳州","文山州","普洱","楚雄州","丽江市","临沧","香港","上海","静安","黄浦","长宁","浦东","嘉定","徐汇","宝山","青浦","金山","虹口","奉贤","杨浦","普陀","松江","闵行","崇明","广东","深圳","东莞","佛山","广州","清远","湛江","汕尾","中山","珠海","梅州","揭阳","江门","汕头","河源","肇庆","阳江","惠州","茂名","韶关","潮州","地区待确认","浙江","境外输入","金华","省十里丰监狱","丽水","舟山","衢州","台州","绍兴","嘉兴","湖州","温州","宁波","杭州","四川","眉山","雅安","德阳","泸州","自贡","攀枝花","凉山","甘孜","阿坝","资阳","成都","巴中","达州","广安","宜宾","南充","乐山","内江","遂宁","广元","绵阳","福建","境外输入","莆田","漳州","地区待确认","宁德","龙岩","南平","三明","泉州","厦门","福州","湖北","襄阳","宜昌","荆州","十堰","孝感","仙桃","黄石","武汉","黄冈","鄂州","天门","潜江","荆门","神农架","随州","咸宁","恩施州","天津","境外输入","宁河区","北辰区","宝坻区","河北区","津南区","南开区","河东区","滨海新区","和平区","外地来津","武清区","东丽区","河西区","西青区","红桥区","陕西","境外输入","榆林","渭南","地区待确认","咸阳","汉中","杨凌","西安","商洛","铜川","延安","宝鸡","安康","韩城","湖南","境外输入","常德","怀化","永州","郴州","益阳","张家界","湘西自治州","岳阳","邵阳","湘潭","株洲","衡阳","长沙","娄底","河南","境外输入","许昌","地区待确认","周口","南阳","信阳","郑州","济源示范区","新乡","安阳","漯河","商丘","驻马店","焦作","开封","平顶山","洛阳","濮阳","鹤壁","三门峡","江苏","徐州","宿迁","南通","苏州","南京","无锡","盐城","连云港","淮安","镇江","常州","扬州","泰州","北京","朝阳","怀柔","顺义","大兴","石景山","延庆","密云","地区待确认","东城","通州","房山","昌平","西城","海淀","丰台","门头沟","内蒙古","呼伦贝尔","包头","呼和浩特","乌兰察布","锡林郭勒","赤峰","通辽","鄂尔多斯","巴彦淖尔","兴安盟","乌海","辽宁","境外输入","丹东","沈阳","大连","铁岭","抚顺","朝阳市","营口","葫芦岛","鞍山","锦州","盘锦","阜新","本溪","辽阳","安徽","境外输入","滁州","合肥","阜阳","宣城","池州","亳州","宿州","六安","黄山","安庆","铜陵","淮北","马鞍山","淮南","蚌埠","芜湖","重庆","境外输入","涪陵区","荣昌区","大足区","綦江区","九龙坡区","丰都县","潼南区","铜梁区","南岸区","沙坪坝区","江北区","万州区","两江新区","巴南区","渝中区","垫江县","云阳县","奉节县","石柱县","长寿区","渝北区","彭水县","忠县","开州区","合川区","巫溪县","大渡口区","巫山县","万盛经开区","酉阳县","璧山区","高新区","永川区","江津区","武隆区","梁平区","城口县","黔江区","秀山县","澳门","地区待确认","广西","境外输入","桂林","北海","防城港","来宾","柳州","河池","南宁","玉林","钦州","贵港","梧州","百色","贺州","宁夏","境外输入","银川","吴忠","固原","中卫","石嘴山","宁东管委会","海南","境外输入","保亭","海口","儋州","万宁","东方","澄迈县","昌江县","三亚","琼海","临高县","陵水县","乐东","文昌","定安县","琼中县","山西","境外输入","晋中","太原","大同","运城","忻州","晋城","长治","朔州","临汾","阳泉","吕梁","西藏","拉萨","河北","石家庄","邢台","保定","地区待确认","廊坊","境外输入","沧州","张家口","唐山","邯郸","衡水","秦皇岛","承德","山东","境外输入","青岛","济宁","济南","临沂","菏泽","淄博","烟台","潍坊","泰安","威海","日照","德州","聊城","滨州","枣庄","黑龙江","境外输入","哈尔滨","绥化","地区待确认","齐齐哈尔","大庆","黑河","牡丹江","大兴安岭","双鸭山","鸡西","鹤岗","七台河","伊春","佳木斯","甘肃","境外输入","兰州","定西","地区待确认","平凉","庆阳","白银","甘南州","天水","陇南","临夏","张掖","金昌","贵州","贵阳","遵义","六盘水","毕节","黔南州","安顺","黔东南州","铜仁","黔西南州","青海","海北州","西宁","吉林","通化","长春","松原","四平","吉林","白城","公主岭","辽源","延边","梅河口市","新疆","喀什","乌鲁木齐","昌吉州","兵团第九师","吐鲁番","第八师石河子","兵团第四师","伊犁州","六师五家渠","兵团第十二师","巴州","阿克苏","第七师","江西","境外输入","南昌","新余","赣州","九江","上饶","抚州","吉安","萍乡","宜春","鹰潭","景德镇","赣江新区"};
}
